### PR TITLE
chore: add docker-compose command to makefile

### LINKED ISSUE #103: Update makefile + readme

### PR DESCRIPTION
**Pull request by robel-yemane**
resolves #103

### CODE REVIEW

**Review by onselakin — APPROVED** [review]

**Comment by robel-yemane** [comment]
@onselakin I see this has been closed but not merged. Do we not want to use the docker-compose that Sevi added? At the moment no script applies that.

**Comment by onselakin** [comment]
> @onselakin I see this has been closed but not merged. Do we not want to use the docker-compose that Sevi added? At the moment no script applies that.

It seems I overlooked this one because we now have a single command that brings up everything. However, it would be better if we added the make targets from this commit back into the code.

**Comment by robel-yemane** [comment]
ok, I'll do that. Yeah I was confused because it was approved and closed :D

**Comment by robel-yemane** [comment]
reopening

**Pull request closed without merging**
